---
- name: Install Docker Compose
  get_url:
    url: "{{ docker_compose_url }}"
    dest: "{{ docker_compose_path }}"
    mode: 0755

- name: Install Docker Compose Module for Python
  pip:
    name: docker-compose
