---
- hosts: all
  remote_user: root
  roles:
    - docker-server
  tags: [ "provision-webservers" ]

- hosts: db_deploy_server
  remote_user: root
  roles:
    - redmine-db-migration
  tags: [ "deploy", "deploy-db" ]

- hosts: all
  remote_user: root
  roles:
    - role: redmine-app
      tags: [ "deploy", "deploy-redmine" ]
    - role: datadog.datadog
      tags: [ "monitoring" ]
